/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/simulations/{simulation_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 시뮬레이션을 JSON 파일로 내보내기 */
        get: operations["export_simulation_api_v1_simulations__simulation_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** JSON 파일 가져오기 (target_year 지정 시 연도 이월 변환) */
        post: operations["import_simulation_api_v1_simulations_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/calculate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 저장 없이 계산 (실시간 미리보기) */
        post: operations["calculate_simulation_api_v1_simulations_calculate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Simulations */
        get: operations["list_simulations_api_v1_simulations_get"];
        put?: never;
        /** Create Simulation */
        post: operations["create_simulation_api_v1_simulations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{simulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation */
        get: operations["get_simulation_api_v1_simulations__simulation_id__get"];
        /** Update Simulation */
        put: operations["update_simulation_api_v1_simulations__simulation_id__put"];
        post?: never;
        /** Delete Simulation */
        delete: operations["delete_simulation_api_v1_simulations__simulation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{simulation_id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 저장본(기준)과 변경안 비교 (저장하지 않음) */
        post: operations["compare_simulation_api_v1_simulations__simulation_id__compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/{simulation_id}/carry-over": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 전년도 시뮬레이션으로 올해 초안 생성 */
        post: operations["carry_over_simulation_api_v1_simulations__simulation_id__carry_over_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 지원 귀속연도 목록 */
        get: operations["list_rule_years_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{tax_year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 귀속연도별 한도·공제율 메타데이터 */
        get: operations["read_rules_api_v1_rules__tax_year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 추천: 추가로 받을 수 있는 공제 항목 (절세액은 계산 엔진이 산출) */
        post: operations["create_recommendations_api_v1_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/couples/optimize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 맞벌이 부부: 부양가족·의료비·교육비 최적 배분 (모든 조합을 계산 엔진으로 계산) */
        post: operations["optimize_couple_api_v1_couples_optimize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/couples/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 맞벌이 부부: 최적 배분에 대한 AI 설명과 추가 팁 */
        post: operations["recommend_couple_allocation_api_v1_couples_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AppliedUnit
         * @enum {string}
         */
        AppliedUnit: "won" | "count";
        /**
         * BreakdownItem
         * @description 공제·세액공제 항목 하나의 계산 내역.
         *
         *     - applied_amount: 공제 적용 대상 금액(입력 사용액·납입액 등) 또는 인원·건수 (applied_unit)
         *     - amount: 최종 공제액 (소득공제액 또는 세액공제액, 원)
         *     - limited: 한도·요건으로 공제액이 줄었는지 여부
         */
        BreakdownItem: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Applied Amount */
            applied_amount: number;
            /** @default won */
            applied_unit: components["schemas"]["AppliedUnit"];
            /** Amount */
            amount: number;
            /**
             * Limited
             * @default false
             */
            limited: boolean;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["BreakdownItem"][];
        };
        /** CalcWarning */
        CalcWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** @default warning */
            level: components["schemas"]["WarningLevel"];
            /** Field */
            field?: string | null;
        };
        /** CardRules */
        CardRules: {
            /** Minimum Usage Rate */
            minimum_usage_rate: string;
            /** Credit Rate */
            credit_rate: string;
            /** Debit Cash Rate */
            debit_cash_rate: string;
            /** Culture Rate */
            culture_rate: string;
            /** Sports Facility Rate */
            sports_facility_rate: string;
            /** Traditional Market Rate */
            traditional_market_rate: string;
            /** Public Transport Rate */
            public_transport_rate: string;
            /** Culture Gross Salary Limit */
            culture_gross_salary_limit: number;
            /** Limit Salary Threshold */
            limit_salary_threshold: number;
            /** Basic Limit Low Income */
            basic_limit_low_income: number;
            /** Basic Limit High Income */
            basic_limit_high_income: number;
            /** Additional Limit Low Income */
            additional_limit_low_income: number;
            /** Additional Limit High Income */
            additional_limit_high_income: number;
            /** Child Basic Limit Per Child Low Income */
            child_basic_limit_per_child_low_income: number;
            /** Child Basic Limit Per Child High Income */
            child_basic_limit_per_child_high_income: number;
            /** Child Basic Limit Max Low Income */
            child_basic_limit_max_low_income: number;
            /** Child Basic Limit Max High Income */
            child_basic_limit_max_high_income: number;
        };
        /** CardUsage */
        CardUsage: {
            /**
             * Credit
             * @default 0
             */
            credit: number;
            /**
             * Debit Cash
             * @default 0
             */
            debit_cash: number;
            /**
             * Culture
             * @default 0
             */
            culture: number;
            /**
             * Sports Facility
             * @default 0
             */
            sports_facility: number;
            /**
             * Traditional Market
             * @default 0
             */
            traditional_market: number;
            /**
             * Public Transport
             * @default 0
             */
            public_transport: number;
        };
        /** ChildCreditRules */
        ChildCreditRules: {
            /** Min Age */
            min_age: number;
            /** First Child */
            first_child: number;
            /** Second Child */
            second_child: number;
            /** Third Plus Child */
            third_plus_child: number;
            /** Birth First */
            birth_first: number;
            /** Birth Second */
            birth_second: number;
            /** Birth Third Plus */
            birth_third_plus: number;
        };
        /** ComparisonResult */
        ComparisonResult: {
            before: components["schemas"]["TaxResult"];
            after: components["schemas"]["TaxResult"];
            /** Saving */
            saving: number;
            /** Tax Year Changed */
            tax_year_changed: boolean;
            /** Metrics */
            metrics: components["schemas"]["MetricDiff"][];
            /** Income Deduction Diffs */
            income_deduction_diffs: components["schemas"]["ItemDiff"][];
            /** Tax Credit Diffs */
            tax_credit_diffs: components["schemas"]["ItemDiff"][];
            /** Input Diffs */
            input_diffs: components["schemas"]["InputDiff"][];
        };
        /** CoupleDependentReason */
        CoupleDependentReason: {
            /** Index */
            index: number;
            /** Name */
            name: string;
            recommended_to: components["schemas"]["Spouse"];
            /** Reason */
            reason: string;
        };
        /** CoupleInput */
        CoupleInput: {
            /** Tax Year */
            tax_year: number;
            primary: components["schemas"]["SimulationInput"];
            spouse: components["schemas"]["SimulationInput"];
            /**
             * Shared Dependents
             * @default []
             */
            shared_dependents: components["schemas"]["SharedDependent"][];
        };
        /** CoupleOptimizationResult */
        CoupleOptimizationResult: {
            /** Tax Year */
            tax_year: number;
            baseline: components["schemas"]["PlanSummary"];
            best: components["schemas"]["PlanSummary"];
            /**
             * Saving
             * @description 현재 배분 대비 최적 배분의 부부 합산 절세액 (지방소득세 포함)
             */
            saving: number;
            /** Alternatives */
            alternatives: components["schemas"]["PlanSummary"][];
            /** Evaluated Count */
            evaluated_count: number;
            best_primary_input: components["schemas"]["SimulationInput"];
            best_spouse_input: components["schemas"]["SimulationInput"];
            best_primary_result: components["schemas"]["TaxResult"];
            best_spouse_result: components["schemas"]["TaxResult"];
        };
        /** CoupleRecommendationResponse */
        CoupleRecommendationResponse: {
            /** Model */
            model: string;
            /** Summary */
            summary: string;
            /** Dependent Reasons */
            dependent_reasons: components["schemas"]["CoupleDependentReason"][];
            /** Tips */
            tips: string[];
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * CreditMethod
         * @enum {string}
         */
        CreditMethod: "itemized" | "standard";
        /**
         * Dependent
         * @description 부양가족 (본인 제외).
         */
        Dependent: {
            /**
             * Name
             * @default
             */
            name: string;
            relation: components["schemas"]["Relation"];
            /** Birth Year */
            birth_year: number;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /**
             * Income Amount
             * @description 연간 소득금액 합계 (근로소득만 있으면 총급여)
             * @default 0
             */
            income_amount: number;
            /**
             * Income Is Salary Only
             * @description 근로소득만 있는지 여부
             * @default false
             */
            income_is_salary_only: boolean;
            /**
             * Born Or Adopted This Year
             * @description 해당 연도 출생·입양 여부
             * @default false
             */
            born_or_adopted_this_year: boolean;
            /**
             * Child Order
             * @description 출생·입양 자녀의 순서
             */
            child_order?: number | null;
        };
        /** DonationCreditRules */
        DonationCreditRules: {
            /** Political Full Credit Limit */
            political_full_credit_limit: number;
            /** Political Full Credit Ratio */
            political_full_credit_ratio: string;
            /** Political Tiers */
            political_tiers: components["schemas"]["RateTier"][];
            /** Hometown Full Credit Limit */
            hometown_full_credit_limit: number;
            /** Hometown Full Credit Ratio */
            hometown_full_credit_ratio: string;
            /** Hometown Rate */
            hometown_rate: string;
            /** Hometown Disaster Rate */
            hometown_disaster_rate: string;
            /** Hometown Annual Limit */
            hometown_annual_limit: number;
            /** General Tiers */
            general_tiers: components["schemas"]["RateTier"][];
            /** General Limit Rate */
            general_limit_rate: string;
            /** Religious Limit Rate */
            religious_limit_rate: string;
            /** Religious Extra Limit Rate */
            religious_extra_limit_rate: string;
        };
        /** Donations */
        Donations: {
            /**
             * Political
             * @default 0
             */
            political: number;
            /**
             * Hometown
             * @default 0
             */
            hometown: number;
            /**
             * Hometown Disaster
             * @default 0
             */
            hometown_disaster: number;
            /**
             * Special
             * @default 0
             */
            special: number;
            /**
             * General
             * @default 0
             */
            general: number;
            /**
             * Religious
             * @default 0
             */
            religious: number;
        };
        /** EarnedIncomeCreditRules */
        EarnedIncomeCreditRules: {
            /** Tax Threshold */
            tax_threshold: number;
            /** Low Rate */
            low_rate: string;
            /** High Rate */
            high_rate: string;
            /** Limit Tiers */
            limit_tiers: components["schemas"]["LimitTier"][];
        };
        /** EarnedIncomeDeductionRules */
        EarnedIncomeDeductionRules: {
            /** Brackets */
            brackets: components["schemas"]["ProgressiveBracket"][];
            /** Max Deduction */
            max_deduction: number;
        };
        /** EducationCreditRules */
        EducationCreditRules: {
            /** Rate */
            rate: string;
            /** Preschool Limit */
            preschool_limit: number;
            /** School Limit */
            school_limit: number;
            /** University Limit */
            university_limit: number;
        };
        /**
         * EducationExpense
         * @description 교육비 1건 = 교육 대상자 1명의 연간 교육비.
         */
        EducationExpense: {
            kind: components["schemas"]["EducationKind"];
            /** Amount */
            amount: number;
            /**
             * Label
             * @default
             */
            label: string;
        };
        /**
         * EducationKind
         * @enum {string}
         */
        EducationKind: "self" | "preschool" | "school" | "university" | "disabled_special";
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** HousingRules */
        HousingRules: {
            /** Subscription Rate */
            subscription_rate: string;
            /** Subscription Payment Limit */
            subscription_payment_limit: number;
            /** Subscription Gross Salary Limit */
            subscription_gross_salary_limit: number;
            /** Rent Loan Rate */
            rent_loan_rate: string;
            /** Rent Loan And Subscription Limit */
            rent_loan_and_subscription_limit: number;
            /** Mortgage Limits */
            mortgage_limits: {
                [key: string]: number;
            };
        };
        /** Income */
        Income: {
            /**
             * Annual Earned Income
             * @description 연간 근로소득 (비과세 포함)
             */
            annual_earned_income: number;
            /**
             * Non Taxable Income
             * @default 0
             */
            non_taxable_income: number;
        };
        /** IncomeDeductionInput */
        IncomeDeductionInput: {
            /**
             * National Pension
             * @default 0
             */
            national_pension: number;
            /**
             * Health Insurance
             * @default 0
             */
            health_insurance: number;
            /**
             * Employment Insurance
             * @default 0
             */
            employment_insurance: number;
            /**
             * Housing Rent Loan Repayment
             * @default 0
             */
            housing_rent_loan_repayment: number;
            /**
             * Long Term Mortgage Interest
             * @default 0
             */
            long_term_mortgage_interest: number;
            mortgage_type?: components["schemas"]["MortgageType"] | null;
            /**
             * Housing Subscription
             * @default 0
             */
            housing_subscription: number;
            /**
             * @default {
             *       "credit": 0,
             *       "debit_cash": 0,
             *       "culture": 0,
             *       "sports_facility": 0,
             *       "traditional_market": 0,
             *       "public_transport": 0
             *     }
             */
            card: components["schemas"]["CardUsage"];
            /**
             * Venture Direct
             * @default 0
             */
            venture_direct: number;
            /**
             * Venture Fund
             * @default 0
             */
            venture_fund: number;
            /**
             * National Growth Fund
             * @default 0
             */
            national_growth_fund: number;
        };
        /** InputDiff */
        InputDiff: {
            /** Path */
            path: string;
            /** Before */
            before: unknown;
            /** After */
            after: unknown;
        };
        /** InsuranceCreditRules */
        InsuranceCreditRules: {
            /** General Limit */
            general_limit: number;
            /** General Rate */
            general_rate: string;
            /** Disabled Limit */
            disabled_limit: number;
            /** Disabled Rate */
            disabled_rate: string;
        };
        /** ItemDiff */
        ItemDiff: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Before */
            before: number;
            /** After */
            after: number;
            /** Delta */
            delta: number;
        };
        /**
         * LimitTier
         * @description 총급여 구간별 한도: ``max(base − (총급여 − lower) × reduction_rate, floor)``.
         */
        LimitTier: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number | null;
            /** Base */
            base: number;
            /** Reduction Rate */
            reduction_rate: string;
            /** Floor */
            floor: number;
        };
        /** LocalIncomeTax */
        LocalIncomeTax: {
            /** Determined Tax */
            determined_tax: number;
            /** Prepaid Tax */
            prepaid_tax: number;
            /** Balance Due */
            balance_due: number;
        };
        /** MedicalCreditRules */
        MedicalCreditRules: {
            /** Threshold Rate */
            threshold_rate: string;
            /** General Limit */
            general_limit: number;
            /** General Rate */
            general_rate: string;
            /** Specific Rate */
            specific_rate: string;
            /** Premature Rate */
            premature_rate: string;
            /** Infertility Rate */
            infertility_rate: string;
            /** Specific Min Age */
            specific_min_age: number;
            /** Specific Max Age At Start */
            specific_max_age_at_start: number;
        };
        /** MedicalExpenses */
        MedicalExpenses: {
            /**
             * General
             * @default 0
             */
            general: number;
            /**
             * Specific
             * @default 0
             */
            specific: number;
            /**
             * Premature
             * @default 0
             */
            premature: number;
            /**
             * Infertility
             * @default 0
             */
            infertility: number;
        };
        /** MethodComparison */
        MethodComparison: {
            method: components["schemas"]["CreditMethod"];
            /** Tax Base */
            tax_base: number;
            /** Calculated Tax */
            calculated_tax: number;
            /** Total Tax Credit */
            total_tax_credit: number;
            /** Determined Tax */
            determined_tax: number;
        };
        /** MetricDiff */
        MetricDiff: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Before */
            before: number;
            /** After */
            after: number;
            /** Delta */
            delta: number;
        };
        /**
         * MortgageType
         * @description 장기주택저당차입금 이자상환액 공제 한도 유형 (소득세법 제52조 제5항).
         * @enum {string}
         */
        MortgageType: "fixed_and_non_deferred_15y" | "fixed_or_non_deferred_15y" | "other_15y" | "fixed_or_non_deferred_10y";
        /**
         * NationalGrowthFundRules
         * @description 국민참여형 국민성장펀드 투자 소득공제 (2026년 귀속 신설).
         */
        NationalGrowthFundRules: {
            /** Tiers */
            tiers: components["schemas"]["RateTier"][];
            /** Max Deduction */
            max_deduction: number;
            /** Min Holding Years */
            min_holding_years: number;
            /** Included In Aggregate Limit */
            included_in_aggregate_limit: boolean;
        };
        /** PensionAccountRules */
        PensionAccountRules: {
            /** Savings Limit */
            savings_limit: number;
            /** Combined Limit */
            combined_limit: number;
            /** High Rate Gross Salary Limit */
            high_rate_gross_salary_limit: number;
            /** High Rate */
            high_rate: string;
            /** Low Rate */
            low_rate: string;
        };
        /** PersonalDeductionRules */
        PersonalDeductionRules: {
            /** Basic Per Person */
            basic_per_person: number;
            /** Elderly Additional */
            elderly_additional: number;
            /** Elderly Min Age */
            elderly_min_age: number;
            /** Disabled Additional */
            disabled_additional: number;
            /** Female Additional */
            female_additional: number;
            /** Female Earned Income Limit */
            female_earned_income_limit: number;
            /** Single Parent Additional */
            single_parent_additional: number;
            /** Dependent Income Limit */
            dependent_income_limit: number;
            /** Dependent Salary Only Limit */
            dependent_salary_only_limit: number;
            /** Ascendant Min Age */
            ascendant_min_age: number;
            /** Descendant Max Age */
            descendant_max_age: number;
            /** Sibling Max Age */
            sibling_max_age: number;
            /** Sibling Min Age */
            sibling_min_age: number;
        };
        /** PlanSummary */
        PlanSummary: {
            /** Assignment */
            assignment: components["schemas"]["Spouse"][];
            /** Primary Determined Tax */
            primary_determined_tax: number;
            /** Spouse Determined Tax */
            spouse_determined_tax: number;
            /** Combined Determined Tax */
            combined_determined_tax: number;
            /** Combined Local Income Tax */
            combined_local_income_tax: number;
            /** Primary Total Balance Due */
            primary_total_balance_due: number;
            /** Spouse Total Balance Due */
            spouse_total_balance_due: number;
            /** Combined Total Balance Due */
            combined_total_balance_due: number;
        };
        /** PrepaidTax */
        PrepaidTax: {
            /**
             * Withholding
             * @description 현 근무지 원천징수 소득세
             * @default 0
             */
            withholding: number;
            /**
             * Previous Employer
             * @description 종전 근무지 결정세액
             * @default 0
             */
            previous_employer: number;
        };
        /**
         * ProgressiveBracket
         * @description ``lower`` 초과 ``upper`` 이하 구간: ``base_amount + (금액 - lower) × rate``.
         */
        ProgressiveBracket: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number | null;
            /** Base Amount */
            base_amount: number;
            /** Rate */
            rate: string;
        };
        /**
         * RateTier
         * @description 누적 금액 ``upper``까지 적용되는 공제율 구간 (upper=None이면 상한 없음).
         */
        RateTier: {
            /** Upper */
            upper: number | null;
            /** Rate */
            rate: string;
        };
        /** Recommendation */
        Recommendation: {
            /** Title */
            title: string;
            category: components["schemas"]["RecommendationCategory"];
            /** Reason */
            reason: string;
            /** Action */
            action: string;
            /** Adjustment Field */
            adjustment_field: string | null;
            /** Adjustment Label */
            adjustment_label: string | null;
            /** Additional Amount */
            additional_amount: number | null;
            /**
             * Estimated Saving
             * @description 계산 엔진이 산출한 예상 절세액(지방소득세 포함, 원). 금액 조정이 없으면 null
             */
            estimated_saving: number | null;
            /** @description 추천을 반영한 입력 (프론트의 '적용' 버튼용) */
            adjusted_input: components["schemas"]["SimulationInput"] | null;
        };
        /**
         * RecommendationCategory
         * @enum {string}
         */
        RecommendationCategory: "income_deduction" | "tax_credit" | "eligibility_check" | "other";
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Model */
            model: string;
            /** Summary */
            summary: string;
            /** Base Total Balance Due */
            base_total_balance_due: number;
            /** Recommendations */
            recommendations: components["schemas"]["Recommendation"][];
            /**
             * Discarded Count
             * @description 절세 효과가 없어 제외한 AI 제안 수
             */
            discarded_count: number;
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * Relation
         * @enum {string}
         */
        Relation: "spouse" | "lineal_ascendant" | "lineal_descendant" | "sibling" | "foster_child";
        /** RentCreditRules */
        RentCreditRules: {
            /** Gross Salary Limit */
            gross_salary_limit: number;
            /** High Rate Gross Salary Limit */
            high_rate_gross_salary_limit: number;
            /** High Rate */
            high_rate: string;
            /** Low Rate */
            low_rate: string;
            /** Payment Limit */
            payment_limit: number;
        };
        /** RulesYears */
        RulesYears: {
            /** Supported Years */
            supported_years: number[];
            /** Default Tax Year */
            default_tax_year: number;
        };
        /**
         * SharedDependent
         * @description 부부 중 누가 공제받을지 정할 부양가족과 그 가족을 위해 지출한 의료비·교육비.
         */
        SharedDependent: {
            /**
             * Name
             * @default
             */
            name: string;
            relation: components["schemas"]["Relation"];
            /** Birth Year */
            birth_year: number;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /**
             * Income Amount
             * @default 0
             */
            income_amount: number;
            /**
             * Income Is Salary Only
             * @default false
             */
            income_is_salary_only: boolean;
            /**
             * Born Or Adopted This Year
             * @default false
             */
            born_or_adopted_this_year: boolean;
            /** Child Order */
            child_order?: number | null;
            /**
             * Medical Expense
             * @description 이 가족을 위해 지출한 의료비
             * @default 0
             */
            medical_expense: number;
            education_kind?: components["schemas"]["EducationKind"] | null;
            /**
             * Education Amount
             * @default 0
             */
            education_amount: number;
            /**
             * @description 현재 공제받을 예정인 사람
             * @default primary
             */
            assigned_to: components["schemas"]["Spouse"];
        };
        /**
         * SimulationComparison
         * @description 저장본(기준)과 변경안 비교. 기준 결과는 현재 규칙으로 다시 계산한 값이다.
         */
        SimulationComparison: {
            base: components["schemas"]["SimulationSummary"];
            /**
             * Snapshot Differs
             * @description 저장 당시 결과 스냅샷과 현재 규칙으로 다시 계산한 기준 결과가 다른지 (세법 규칙 변경 등)
             */
            snapshot_differs: boolean;
            comparison: components["schemas"]["ComparisonResult"];
        };
        /** SimulationCreate */
        SimulationCreate: {
            /** Name */
            name: string;
            input: components["schemas"]["SimulationInput"];
        };
        /**
         * SimulationExport
         * @description JSON 내보내기/가져오기 문서.
         */
        SimulationExport: {
            /** Schema Version */
            schema_version: number;
            /** Tax Year */
            tax_year: number;
            /** Name */
            name: string;
            /** Exported At */
            exported_at?: string | null;
            /** Input */
            input: {
                [key: string]: unknown;
            };
        };
        /** SimulationInput */
        SimulationInput: {
            /** Tax Year */
            tax_year: number;
            income: components["schemas"]["Income"];
            /**
             * @default {
             *       "withholding": 0,
             *       "previous_employer": 0
             *     }
             */
            prepaid_tax: components["schemas"]["PrepaidTax"];
            taxpayer: components["schemas"]["Taxpayer"];
            /**
             * Dependents
             * @default []
             */
            dependents: components["schemas"]["Dependent"][];
            /**
             * @default {
             *       "national_pension": 0,
             *       "health_insurance": 0,
             *       "employment_insurance": 0,
             *       "housing_rent_loan_repayment": 0,
             *       "long_term_mortgage_interest": 0,
             *       "housing_subscription": 0,
             *       "card": {
             *         "credit": 0,
             *         "culture": 0,
             *         "debit_cash": 0,
             *         "public_transport": 0,
             *         "sports_facility": 0,
             *         "traditional_market": 0
             *       },
             *       "venture_direct": 0,
             *       "venture_fund": 0,
             *       "national_growth_fund": 0
             *     }
             */
            deductions: components["schemas"]["IncomeDeductionInput"];
            /**
             * @default {
             *       "pension_savings": 0,
             *       "irp": 0,
             *       "insurance_general": 0,
             *       "insurance_disabled": 0,
             *       "medical": {
             *         "general": 0,
             *         "infertility": 0,
             *         "premature": 0,
             *         "specific": 0
             *       },
             *       "education": [],
             *       "donations": {
             *         "general": 0,
             *         "hometown": 0,
             *         "hometown_disaster": 0,
             *         "political": 0,
             *         "religious": 0,
             *         "special": 0
             *       },
             *       "monthly_rent": 0
             *     }
             */
            credits: components["schemas"]["TaxCreditInput"];
        };
        /** SimulationRead */
        SimulationRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Tax Year */
            tax_year: number;
            /** Schema Version */
            schema_version: number;
            /** Determined Tax */
            determined_tax: number;
            /** Total Balance Due */
            total_balance_due: number;
            /** Source Simulation Id */
            source_simulation_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            input: components["schemas"]["SimulationInput"];
            result: components["schemas"]["TaxResult"];
        };
        /** SimulationSummary */
        SimulationSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Tax Year */
            tax_year: number;
            /** Schema Version */
            schema_version: number;
            /** Determined Tax */
            determined_tax: number;
            /** Total Balance Due */
            total_balance_due: number;
            /** Source Simulation Id */
            source_simulation_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SimulationUpdate */
        SimulationUpdate: {
            /** Name */
            name: string;
            input: components["schemas"]["SimulationInput"];
        };
        /** SimulationWithWarnings */
        SimulationWithWarnings: {
            simulation: components["schemas"]["SimulationRead"];
            /** Warnings */
            warnings: components["schemas"]["CalcWarning"][];
        };
        /**
         * Spouse
         * @enum {string}
         */
        Spouse: "primary" | "spouse";
        /** TaxCreditInput */
        TaxCreditInput: {
            /**
             * Pension Savings
             * @default 0
             */
            pension_savings: number;
            /**
             * Irp
             * @default 0
             */
            irp: number;
            /**
             * Insurance General
             * @default 0
             */
            insurance_general: number;
            /**
             * Insurance Disabled
             * @default 0
             */
            insurance_disabled: number;
            /**
             * @default {
             *       "general": 0,
             *       "specific": 0,
             *       "premature": 0,
             *       "infertility": 0
             *     }
             */
            medical: components["schemas"]["MedicalExpenses"];
            /**
             * Education
             * @default []
             */
            education: components["schemas"]["EducationExpense"][];
            /**
             * @default {
             *       "political": 0,
             *       "hometown": 0,
             *       "hometown_disaster": 0,
             *       "special": 0,
             *       "general": 0,
             *       "religious": 0
             *     }
             */
            donations: components["schemas"]["Donations"];
            /**
             * Monthly Rent
             * @default 0
             */
            monthly_rent: number;
        };
        /**
         * TaxRateBracket
         * @description 기본세율 구간 (누진공제액 방식): 세액 = 과세표준 × rate − progressive_deduction.
         */
        TaxRateBracket: {
            /** Upper */
            upper: number | null;
            /** Rate */
            rate: string;
            /** Progressive Deduction */
            progressive_deduction: number;
        };
        /** TaxResult */
        TaxResult: {
            /** Tax Year */
            tax_year: number;
            /** Rules Verified */
            rules_verified: boolean;
            /** Annual Earned Income */
            annual_earned_income: number;
            /** Non Taxable Income */
            non_taxable_income: number;
            /** Gross Salary */
            gross_salary: number;
            earned_income_deduction: components["schemas"]["BreakdownItem"];
            /** Earned Income Amount */
            earned_income_amount: number;
            applied_method: components["schemas"]["CreditMethod"];
            /** Method Comparison */
            method_comparison: components["schemas"]["MethodComparison"][];
            /** Income Deductions */
            income_deductions: components["schemas"]["BreakdownItem"][];
            /** Total Income Deduction */
            total_income_deduction: number;
            /** Tax Base */
            tax_base: number;
            /** Tax Rate */
            tax_rate: string;
            /** Calculated Tax */
            calculated_tax: number;
            /** Tax Reduction */
            tax_reduction: number;
            /** Tax Credits */
            tax_credits: components["schemas"]["BreakdownItem"][];
            /** Total Tax Credit */
            total_tax_credit: number;
            /** Determined Tax */
            determined_tax: number;
            /** Prepaid Tax */
            prepaid_tax: number;
            /** Balance Due */
            balance_due: number;
            local_income_tax: components["schemas"]["LocalIncomeTax"];
            /** Total Balance Due */
            total_balance_due: number;
            /** Warnings */
            warnings: components["schemas"]["CalcWarning"][];
            /** Disclaimer */
            disclaimer: string;
        };
        /**
         * TaxRules
         * @description 한 귀속연도의 근로소득 연말정산 규칙 묶음.
         */
        TaxRules: {
            /** Tax Year */
            tax_year: number;
            /** Verified */
            verified: boolean;
            /** Notes */
            notes: string[];
            earned_income_deduction: components["schemas"]["EarnedIncomeDeductionRules"];
            personal: components["schemas"]["PersonalDeductionRules"];
            housing: components["schemas"]["HousingRules"];
            card: components["schemas"]["CardRules"];
            venture: components["schemas"]["VentureRules"];
            national_growth_fund: components["schemas"]["NationalGrowthFundRules"] | null;
            /** Aggregate Deduction Limit */
            aggregate_deduction_limit: number;
            /** Tax Rate Brackets */
            tax_rate_brackets: components["schemas"]["TaxRateBracket"][];
            earned_income_credit: components["schemas"]["EarnedIncomeCreditRules"];
            child_credit: components["schemas"]["ChildCreditRules"];
            pension_account: components["schemas"]["PensionAccountRules"];
            insurance_credit: components["schemas"]["InsuranceCreditRules"];
            medical_credit: components["schemas"]["MedicalCreditRules"];
            education_credit: components["schemas"]["EducationCreditRules"];
            donation_credit: components["schemas"]["DonationCreditRules"];
            rent_credit: components["schemas"]["RentCreditRules"];
            /** Standard Credit */
            standard_credit: number;
            /** Marriage Credit */
            marriage_credit: number | null;
            /** Local Income Tax Rate */
            local_income_tax_rate: string;
        };
        /** Taxpayer */
        Taxpayer: {
            /** Birth Year */
            birth_year: number;
            /**
             * Is Female
             * @default false
             */
            is_female: boolean;
            /**
             * Is Married
             * @description 배우자가 있는지 여부
             * @default false
             */
            is_married: boolean;
            /**
             * Is Household Head
             * @default false
             */
            is_household_head: boolean;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /**
             * Is Homeless
             * @description 무주택 세대주(또는 요건 충족 세대원) 여부
             * @default false
             */
            is_homeless: boolean;
            /**
             * Marriage Registered This Year
             * @description 해당 연도 혼인신고 여부
             * @default false
             */
            marriage_registered_this_year: boolean;
        };
        /** VentureRules */
        VentureRules: {
            /** Direct Tiers */
            direct_tiers: components["schemas"]["RateTier"][];
            /** Fund Rate */
            fund_rate: string;
            /** Income Limit Rate */
            income_limit_rate: string;
        };
        /**
         * WarningLevel
         * @enum {string}
         */
        WarningLevel: "info" | "warning";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    export_simulation_api_v1_simulations__simulation_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationExport"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    import_simulation_api_v1_simulations_import_post: {
        parameters: {
            query?: {
                target_year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationExport"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationWithWarnings"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    calculate_simulation_api_v1_simulations_calculate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxResult"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_simulations_api_v1_simulations_get: {
        parameters: {
            query?: {
                tax_year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationSummary"][];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_simulation_api_v1_simulations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRead"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_simulation_api_v1_simulations__simulation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRead"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_simulation_api_v1_simulations__simulation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRead"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_simulation_api_v1_simulations__simulation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    compare_simulation_api_v1_simulations__simulation_id__compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationComparison"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    carry_over_simulation_api_v1_simulations__simulation_id__carry_over_post: {
        parameters: {
            query: {
                target_year: number;
                /** @description 급여 인상률(%) */
                salary_increase_rate?: number | string | null;
            };
            header?: never;
            path: {
                simulation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationWithWarnings"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_rule_years_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesYears"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_rules_api_v1_rules__tax_year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tax_year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxRules"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_recommendations_api_v1_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI 응답 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI 미설정 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    optimize_couple_api_v1_couples_optimize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoupleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleOptimizationResult"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recommend_couple_allocation_api_v1_couples_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoupleInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoupleRecommendationResponse"];
                };
            };
            /** @description 잘못된 요청 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 리소스 없음 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI 응답 실패 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI 미설정 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
